all:
	@${MAKE} ${MAKEFLAGS} -C daemon
	@${MAKE} ${MAKEFLAGS} -C shell

clean:
	@${MAKE} ${MAKEFLAGS} -C daemon clean
	@${MAKE} ${MAKEFLAGS} -C shell clean

cleandir:
	@${MAKE} ${MAKEFLAGS} -C daemon cleandir
	@${MAKE} ${MAKEFLAGS} -C shell cleandir
